### PR TITLE
fix: new key action triggering

### LINKED ISSUE #9: ⌨️ bindings editor
- new component
- salvage code from gridboard if possible

### PR DESCRIPTION
**Pull request by zenkyuv**

### CODE REVIEW

File: s/elements/bindings-editor/utils/loadBindings.ts [hunk 1]
```diff
@@ -1,11 +1,28 @@
...
+		const savedBindings = localStorage?.getItem('bindings')!;
+		const savedBindingsJSON:Bindings = JSON.parse(savedBindings)
+		setBindings(savedBindingsJSON)
+	})
+}
+
+export function loadLocalStorageBindings() {
 	const savedBindings = localStorage?.getItem('bindings')!;
-	const savedBindingsJSON: Bindings = JSON.parse(savedBindings)
+	const savedBindingsJSON:Bindings = JSON.parse(savedBindings)
```
Comment (PaulAroo) [inline s/elements/bindings-editor/utils/loadBindings.ts:15]: image

just curious as to why the space between the variable name and the type was removed
it's kinda more readable when it's spaced, yeah?

**Comment by PaulAroo** [comment]
I think this looks okay 👍🏽

File: s/elements/bindings-editor/utils/loadBindings.ts (hunk 1 above)
Comment (chase-moskal) [reply s/elements/bindings-editor/utils/loadBindings.ts:15]: a space would be preferable here -- but it's no big deal

we're in an early stage of development -- one day in the future, we'll apply more rigid style rules and linters and such

in the past i've been too demanding in terms of syntactical perfection :D

**Review by chase-moskal — CHANGES_REQUESTED** [review]
looking good, i just want to understand more about the *dispatching* of the storage event, see other comment

File: s/elements/bindings-editor/views/buttons.ts [hunk 2]
```diff
@@ -10,6 +10,7 @@ export const ButtonsView = view(use => (keybinds: Bindings, setKeybinds: StateSe
 	const applyBindings = () => {
 		localStorage.setItem('bindings', JSON.stringify(keybinds));
 		setKeybinds(loadBindings())
+		window.dispatchEvent(new Event("storage"));
```
[the remark this answers is not in the document]
Comment (zenkyuv) [reply s/elements/bindings-editor/views/buttons.ts:13]: yeah so i needed to dispatch that event because the storage listener wasnt running when i added to storage, ive read that it doesnt run if these things happens in the same context but they werent ?

File: s/elements/context/element.ts [hunk 3]
```diff
@@ -21,7 +22,9 @@ export const NubContext = element<{
 	}).render(use => {
 
 	const [actions] = use.state(stateForActions)
-	const [bindings] = use.state<Bindings>(use.element.bindingsJson ?? defaultBindings)
+	const [bindings, setBindings] = use.state<Bindings>(loadLocalStorageBindings() ?? use.element.bindingsJson ?? defaultBindings)
+
+	listenForLocalStorageBindings(setBindings)
```
Comment (chase-moskal) [inline s/elements/context/element.ts:27]: this is being called on every render, and it adds a new `storage` event listener on the window, every time.

instead, we only want to add one storage listener.

i think we should do something like this instead:

```js
use.setup(() => {
  const listener = setupStorageEventHandling(setBindings)
  window.addEventListener("storage", listener)
  return () => window.removeEventListener("storage", listener)
})
```

that's a proper setup that will even unsubscribe the listener when the component is disconnected.

it's best if we extract that logic out into another file, so it's just:

```js
use.setup(listenForStorageEventsToUpdateBindings(window, setBindings))
```

File: s/elements/context/element.ts [hunk 4]
```diff
@@ -21,7 +22,9 @@ export const NubContext = element<{
 	}).render(use => {
 
 	const [actions] = use.state(stateForActions)
-	const [bindings] = use.state<Bindings>(use.element.bindingsJson ?? defaultBindings)
+	const [bindings, setBindings] = use.state<Bindings>(loadLocalStorageBindings() ?? use.element.bindingsJson ?? defaultBindings)
```
Comment (chase-moskal) [inline s/elements/context/element.ts:25]: i like this `loadLocalStorageBindings() ?? use.element.bindingsJson ?? defaultBindings`

technically, this expression is evaluated on every render. that's too often.

we can tweak this line to improve peformance, like this:

```ts
const [bindings, setBindings] = use.state<Bindings>(
  () => loadLocalStorageBindings() ?? use.element.bindingsJson ?? defaultBindings
)
```

now it's using a state initializer function, which will only be executed one time to find the initial value

File: s/elements/bindings-editor/views/buttons.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (chase-moskal) [reply s/elements/bindings-editor/views/buttons.ts:13]: let's remove the dispatching of storage events
  - keep listening to storage events, that's a good idea, no problems there (we just need to stop dispatching storage events)
  - instead of dispatching an event just to trigger our own handler, let's just call that handler functionality directly. we don't need to use the event system to "talk to ourselves" so to speak.

**Review by chase-moskal — CHANGES_REQUESTED** [review]
let's make these changes before merging
